### ISSUE TITLE
HTML Body Tag

### ISSUE THREAD

**Issue by cyouh95** [nprater86/teacozy#2]
(Subtlety) In HTML documents, the structure is usually as follows where the `head` and `body` tags lie between the `html` tags:

```html
<!DOCTYPE html>
<html>
<head></head>
<body></body>
</html>
```

But remember that _only_ the content between the `body` tag is being displayed on the webpage (the information between the `head` tags is just meta data). Thus, in your css file, you can specify all the general page properties for the `body` tag rather than the `html` tag:

```css
body {
  font-family: Helvetica;
  font-size: 22px;
  color: seashell;
  background-color: black;
  opacity: 0.9;
  text-align: center;
  margin: 0;
}
```

https://github.com/nprater86/teacozy/blob/master/resources/css/style.css#L1-L13
