### ISSUE TITLE
Avoiding Repetition in CSS File

### ISSUE THREAD

**Issue by cyouh95** [nprater86/teacozy#3]
(Simplify) It looks like `display: flex;` appears 9 times in your css file. For cases like this, consider defining another class (such as **flex-container** below) that you can assign to all HTML elements that this property should apply to:

```css
.flex-container {
  display: flex;
}
```

https://github.com/nprater86/teacozy/blob/master/resources/css/style.css
